config/routes.rb
App1::Application.routes.draw do
  
  resources :calcs
  get "calcs/index"
  match 'new_calc' => "Calcs#new"
  match 'all' => "Calcs#index", :as => "all_calcs"
  match ':aktsia_nimi' => 'Calcs#index', :as => 'aktsia_nimi_calcs'
  
  

   root :to => 'calcs#index'

end

app/models/calc.rb
class Calc < ActiveRecord::Base
  attr_accessible :aastad, :aktsia_nimi, :hind, :kogus, :protsent
  
  validates :aastad, :presence => true, :numericality => { :only_integer => true, :greater_than_or_equal_to => 0,:less_than_or_equal_to => 100}
  validates :aktsia_nimi, :presence => true, :length => {:minimum => 1}
  validates :hind, :presence => true, :numericality => {:greater_than_or_equal_to => 0, :less_than_or_equal_to => 10000000}
  validates :kogus, :presence => true, :numericality => { :only_integer => true, :greater_than_or_equal_to => 0 , :less_than_or_equal_to => 100000000}
  validates :protsent, :presence => true, :numericality => { :less_than_or_equal_to => 100, :greater_than_or_equal_to => 0 }
  
  def arvuta
    puts "jei"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/calcs_controller.rb
class CalcsController < ApplicationController
  # GET /calcs
  # GET /calcs.json
  def index
    @calcs = Calc.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @calcs }
    end
  end

  # GET /calcs/1
  # GET /calcs/1.json
  def show
    @calc = Calc.find(params[:id])
    @vari = Calc.new(params[:calc])
    @result = @vari.arvuta

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @calc }
    end
  end

  # GET /calcs/new
  # GET /calcs/new.json
  def new
    @calc = Calc.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @calc }
    end
  end

  # GET /calcs/1/edit
  def edit
    @calc = Calc.find(params[:id])
  end

  # POST /calcs
  # POST /calcs.json
  def create
    @calc = Calc.new(params[:calc])

    respond_to do |format|
      if @calc.save
        format.html { redirect_to @calc, notice: 'Calc was successfully created.' }
        format.json { render json: @calc, status: :created, location: @calc }
      else
        format.html { render action: "new" }
        format.json { render json: @calc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /calcs/1
  # PUT /calcs/1.json
  def update
    @calc = Calc.find(params[:id])

    respond_to do |format|
      if @calc.update_attributes(params[:calc])
        format.html { redirect_to @calc, notice: 'Calc was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @calc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calcs/1
  # DELETE /calcs/1.json
  def destroy
    @calc = Calc.find(params[:id])
    @calc.destroy

    respond_to do |format|
      format.html { redirect_to calcs_url }
      format.json { head :no_content }
    end
  end
  
    
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calcs_helper.rb
module CalcsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/calcs/_form.html.erb
<%= form_for(@calc) do |f| %>
  <% if @calc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calc.errors.count, "error") %> prohibited this calc from being saved:</h2>

      <ul>
      <% @calc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :aktsia_nimi %><br />
    <%= f.text_field :aktsia_nimi %>
  </div>
  <div class="field">
    <%= f.label :hind %><br />
    <%= f.text_field :hind %>
  </div>
  <div class="field">
    <%= f.label :kogus %><br />
    <%= f.number_field :kogus %>
  </div>
  <div class="field">
    <%= f.label :protsent %><br />
    <%= f.text_field :protsent %>
  </div>
  <div class="field">
    <%= f.label :aastad %><br />
    <%= f.number_field :aastad %>
  </div>
  <div class="actions">
    <%= f.submit :Kinnita %>
  </div>
<% end %>

app/views/calcs/edit.html.erb
<h1>Muutmine</h1>

<%= render 'form' %>

<%= link_to 'Näita', @calc %> |
<%= link_to 'Tagasi', calcs_path %>

app/views/calcs/index.html.erb
<h1>Aktsiad ja andmed</h1>

<table>
  <tr>
    <th>Aktsia nimi</th>
    <th>Hind</th>
    <th>Kogus</th>
    <th>Protsent</th>
    <th>Aastad</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @calcs.each do |calc| %>
  <tr>
    <td><%= calc.aktsia_nimi %></td>
    <td><%= calc.hind %></td>
    <td><%= calc.kogus %></td>
    <td><%= calc.protsent %></td>
    <td><%= calc.aastad %></td>
    <td><%= link_to 'Näita', calc %></td>
    <td><%= link_to 'Muuda', edit_calc_path(calc) %></td>
    <td><%= link_to 'Eemalda', calc, method: :delete, data: { confirm: 'Oled kindel?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Sisesta uued andmed', new_calc_path %>

app/views/calcs/new.html.erb
<h1>Sisesta uued andmed</h1>

<%= render 'form' %>



<%= link_to 'Tagasi', calcs_path %>

app/views/calcs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Aktsia nimi:</b>
  <%= @calc.aktsia_nimi %>
</p>

<p>
  <b>Hind:</b>
  <%= @calc.hind %>
</p>

<p>
  <b>Kogus:</b>
  <%= @calc.kogus %>
</p>

<p>
  <b>Protsent:</b>
  <%= @calc.protsent %>
</p>

<p>
  <b>Aastad:</b>
  <%= @calc.aastad %>
</p>

<p><b>Tabel: </b></p>
 <p><%= @vari.arvuta %>
 </p>
 
<p><b>Graafik: </b></p>

<%= link_to 'Muuda', edit_calc_path(@calc) %> |
<%= link_to 'Tagasi', calcs_path %>

app/views/home/index.html.erb
<h1>Hello, Rails</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App1</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>